title: "Magueye Sane Mbaye | Software Developer"

description: "Software Development Portfolio — Web Development, Java, Python, C++, MySQL, WordPress and Software Engineering."

author: "Magueye Sane Mbaye"

theme: jekyll-theme-cayman

show_downloads: false

github:
  username: Maxi-prime
